<?php include "headerTeam.phtml" ?>

<!---------- Body starts --------------->

<table>
    <?php 

        echo "<br><h2><center> Created by</center></h2>";
        echo " <br><table align='center'><tr>";
        echo "<td> Erdem Alpakaya </td><td>     16226114    </td></tr>";
        echo "<td> Junghoe Hwang </td><td>     16242934    </td></tr>";
        echo "<td> Robert Harper </td><td>     96066910    </td></tr></table>";
    ?>
</table>

<br>
<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>