<?php include "headerTeam.phtml" ?>
<!---------- Body starts --------------->
<?php

session_start();
if($complete){
  echo"<h2><center> Your account " . $acc_num. " has been created </h2>";
  echo"
  <script>
  setTimeout(function () {
   window.location.href= 'http://localhost:8000/account';},5000);
  </script>
  ";

}else{
  echo "<form action= '$action' method='POST'>
  <h2> Are you sure to create an account? </h2>
  <input type='submit'  class='button' name='create' value='Yes' />
  <input type='submit'  class='button' name='back' value='No' />
  </form>";
}
echo " <p><center>Go back to account page <a href=" .$linkTo('accountIndex'). ">back</a>.</center></p>";
?>

<br>

    <!---------- Body ends -------------------->
<?php include "footer.phtml" ?>