<?php include "header.phtml" ?>
    <!---------- Body starts --------------->
    <h1>Welcome to </h1>
    Please sign in!
    <table>
        <?php foreach ($accounts as $account) { ?>
            <tr>
                <td><?= $account->getId() ?></td>
                <td><?= $account->getName() ?></td>
                <td><a href= <?= $linkTo('accountDelete', ['id' => $account->getId()]);?> >delete</a></td>
            </tr>
        <?php } ?>
    </table>

    <a href=<?= $linkTo('accountCreate'); ?>>Create new account.</a>
    <a href=<?= $linkTo('accountCreate'); ?>>Create new account.</a>
    <br>
    <!---------- Body ends -------------------->
<?php include "footer.phtml" ?>