<?php include "headerTeam.phtml" ?>

<!---------- Body starts --------------->

<table>
    <?php 
    if(empty($accounts)){
        echo "<h2> Don't have Any Accounts </h2>";  
    }else{
        echo "<h2> The accounts are:</h2>";
        echo " <tr>";
        echo "<td> Account Number </td>";
        echo "<td> Customer Id </td>";
        echo "<td> Balance </td></tr>";
        foreach ($accounts as $account) { 
            echo "
        <td>". $account->getAccountNum() . "</td>
        <td>".  $account->getCustomerId() ." </td>
        <td>". $account->getBalance() ."</td>
        <td> <a href=" .$linkTo('accountDelete', ['id' => $account->getAccountNum()]) . " >delete</a></td>
    </tr> ";
        }
    }
    ?>
</table>

<a href=<?= $linkTo('accountCreate'); ?>>Create new account.</a>
<br>
<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>