<?php include "header.phtml" ?>
<!---------- Body starts --------------->
<h1 align="center">Welcome to Account Management Ltd </h1>
<a href=<?= $linkTo('accountCreate'); ?>>Sign up</a>
<br>
<a href=<?= $linkTo('accountCreate'); ?>>Log in</a>
<br>
<a href=<?= $linkTo('accountCreate'); ?>>Create new account. - maybe after login</a>
<br>

<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>