<?php include "header.phtml" ?>
<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<style>
    body {font-family: Arial, Helvetica, sans-serif;}

    .navbar {
        width: 100%;
        background-color: #34495E;
        overflow: auto;
    }

    .navbar a {
        float: left;
        padding: 20px;
        color: white;
        text-decoration: none;
        font-size: 25px;
    }

    .navbar a:hover {
        background-color: #000;
    }

    /* Right-aligned section inside the top navigation */
    .topnav-right {
        float: right;
    }

    .active {
        background-color: #5499C7;
    }

    @media screen and (max-width: 500px) {
        .navbar a {
            float: none;
            display: block;
        }
    }
</style>
<body>

<div class="navbar">
    <a class="active" href=<?= $linkTo('Home'); ?>><i class="fas fa-piggy-bank"></i> FNBank</a>
    <div class="topnav-right">
        <a href="#"><i class="fa fa-fw fa-search"></i> About Us</a>
        <?php 
        session_start();
        if ($_SESSION['loggedin']){ 
            echo "<a href= ".$linkTo('accountIndex')."> <i class='far fa-hand-point-right'></i> Account </a>";
        }
        else{
            echo "<a href= ".$linkTo('Signup')."> <i class='far fa-hand-point-right'></i> Sign-up</a>";
        }
        if ($_SESSION['loggedin']){ 
            echo "<a href= ".$linkTo('Logout')."> <i class='far fa-hand-point-right'></i> Logout</a>";
        }
        else{
            echo "<a href= ".$linkTo('Login')."> <i class='far fa-hand-point-right'></i> Login</a>";
        }
        ?>
    </div>
</div>

</body>
</html>

