<?php include "header.phtml" ?>

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Add icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        body {font-family: Arial, Helvetica, sans-serif;}
        * {box-sizing: border-box;}

        .input-container {
            display: -ms-flexbox; /* IE10 */
            display: flex;
            width: 100%;
            margin-bottom: 15px;
        }

        .icon {
            padding: 10px;
            background: #34495E;
            color: white;
            min-width: 50px;
            text-align: center;
        }

        .input-field {
            width: 100%;
            padding: 10px;
            outline: none;
        }

        .input-field:focus {
            border: 2px solid dodgerblue;
        }

        /* Set a style for the submit button */
        .btn {
            background-color: #16A085;
            color: white;
            padding: 15px 20px;
            border: none;
            cursor: pointer;
            width: 100%;
            opacity: 0.9;
        }

        .btn:hover {
            opacity: 1;
        }
    </style>
</head>
<body>

<form action= "<?php $action; ?>" style="max-width:500px;margin:auto" method="POST">
    <h2>Login</h2>
    <div class="input-container">
        <i class="fa fa-user icon"></i>
        <input class="input-field" type="text" placeholder="Username" name="username">
    </div>


    <div class="input-container">
        <i class="fa fa-key icon"></i>
        <input class="input-field" type="password" placeholder="Password" name="psw">
    </div>

    <?php 
    if(strcmp($login_error,"")!==0){
        echo '<font color="red"><center>'. $login_error.' </center></font><br>';
    }
    ?>

    <button type="submit" class="btn">Login</button>
    <div class="container signin">
        <p>Do not have an account? <a href=<?= $linkTo('Signup'); ?>>Sign up</a>.</p>
    </div>
</form>

</body>
</html>

<?php include "footer.phtml" ?>
