<?php include "headerTeam.phtml" ?>
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Add icon library -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <style>
        body {font-family: Arial, Helvetica, sans-serif;}
        * {box-sizing: border-box;}

        .input-container {
            display: ruby-text-container; /* IE10 */
            display: flex;
            width: 100%;
            margin-bottom: 15px;
        }

        .icon {
            padding: 10px;
            background: #34495E;
            color: white;
            min-width: 50px;
            text-align: center;
        }

        .input-field {
            width: 100%;
            padding: 10px;
            outline: none;
        }

        .input-field:focus {
            border: 2px solid dodgerblue;
        }

        /* Set a style for the submit button */
        .btn {
            background-color: #16A085;
            color: white;
            padding: 15px 20px;
            border: none;
            cursor: pointer;
            width: 100%;
            opacity: 0.9;
        }

        .btn:hover {
            opacity: 1;
        }
    </style>
</head>
<body>

<form action= "<?php $action; ?>" style="max-width:500px;margin:auto" method="POST">
    <h2>Sign Up</h2>
    <div class="input-container">
        <i class="far fa-user icon"></i>
        <input class="input-field" type="text" placeholder="First Name" name="fname" required>
    </div>

    <div class="input-container">
        <i class="far fa-user icon"></i>
        <input class="input-field" type="text" placeholder="Last name" name="lname" required>
    </div>

    <div class="input-container">
        <i class="fa fa-envelope icon"></i>
        <input class="input-field" type="text" placeholder="Address" name="address" required>
    </div>
    
    <div class="input-container">
        <i class="fas fa-user-shield icon"></i>
        <input class="input-field" type="text" placeholder="Username (log in ID) " name="username" required>
    </div>

    <div class="input-container">
        <i class="fa fa-key icon"></i>
        <input class="input-field" type="password" placeholder="Password" name="psw" required>
    </div>

        <div class="input-container">
        <i class="fa fa-key icon"></i>
        <input class="input-field" type="password" placeholder="Confirm Password" name="cfmpsw" required>
    </div>
    <?php 
    if(strcmp($error,"")!==0){
        echo '<font color="red"><center>'. $error. 'Re-type details. </center></font><br>';
    }
    ?>

    <button type="submit" class="btn">Register</button>

    <div class="container signin">
        <p>Already have an account? <a href=<?= $linkTo('Login'); ?>>Sign in</a>.</p>
    </div>
</form>

</body>
</html>

<?php include "footer.phtml" ?>
<!-- This is orj sign up -->