<?php include "header.phtml" ?>
    <!---------- Body starts --------------->
<?php
if(isset($accountName)){
    echo 'Account <?= $accountName ?> created successfully.';
}
?>
    <form action="<?php echo $action; ?>" method="get">
        Your First Name: <input type="text" name="FirstName"><br>
        Your Last Name: <input type="text" name="LastName"><br>
        <input type="submit" value="Create">
    </form>
    <br>
    <a href=<?= $linkTo('accountIndex'); ?>>Back</a>
    <br>
    <!---------- Body ends -------------------->
<?php include "footer.phtml" ?>