<?php include "header.phtml" ?>

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Add icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        body {font-family: Arial, Helvetica, sans-serif;}
        * {box-sizing: border-box;}

        .input-container {
            display: -ms-flexbox; /* IE10 */
            display: flex;
            width: 100%;
            margin-bottom: 15px;
        }

        .icon {
            padding: 10px;
            background: #34495E;
            color: white;
            min-width: 50px;
            text-align: center;
        }

        .input-field {
            width: 100%;
            padding: 10px;
            outline: none;
        }

        .input-field:focus {
            border: 2px solid dodgerblue;
        }

        /* Set a style for the submit button */
        .btn {
            background-color: #16A085;
            color: white;
            padding: 15px 20px;
            border: none;
            cursor: pointer;
            width: 100%;
            opacity: 0.9;
        }

        .btn:hover {
            opacity: 1;
        }
    </style>
</head>
<body>

<form action= "<?php $action; ?>" style="max-width:500px;margin:auto" method="POST">
    <h3>How much money would you like to withdraw?</h3>
    <?php echo "<h4>Current Balance is  $balance </h4>"; ?> 
    <div class="input-container">
        <i class="fa fa-user icon"></i>
        <input class="input-field" type="text" placeholder="Amount" name="amount" oninput="check(this)">
    </div>
    <?php 
    if(strcmp($withdraw_error,"")!==0){
        echo '<font color="red"><center>'. $withdraw_error.' Try again. </center></font><br>';
    }
    if(strcmp($transaction,"")!==0){
        echo '<font color="blue"><center>'. $transaction.' Thank you for using FBBank. </center></font><br>';
    }
    ?>
    <button type="submit" class="btn">Submit</button>
    <div class="container withdraw">
        <p>Go back to account page <a href=<?= $linkTo('accountIndex'); ?>>back</a>.</p>
    </div>
</form>
<script>
 function check(input) {
   if (input.value < 0) {
     input.setCustomValidity('The number must be greater than zero.');
   } else {
     // input is fine -- reset the error message
     input.setCustomValidity('');
   }
 }
</script>

</body>
</html>

<?php include "footer.phtml" ?>
